
```{r}

#Laden der Pakete
library("tidyverse")
library("shiny")
library("leaflet")
library("rnaturalearth")

```


```{r}

# Lade die CSV-Dateien wieder in DataFrames
regendaten_teil1 <- read.csv("regendaten_teil1.csv")
regendaten_teil2 <- read.csv("regendaten_teil2.csv")
regendaten_teil3 <- read.csv("regendaten_teil3.csv")

# Füge die DataFrames wieder zusammen
regendaten <- rbind(regendaten_teil1, regendaten_teil2, regendaten_teil3)
#Laden der CSV Datei welche die Durchschnittswerten enthält, löschen von Na Werten
new_df <- read.csv("new_df.csv")
new_df <- new_df[rowSums(is.na(new_df)) < ncol(new_df), ]

```


```{r}

#Länderumriss Koordinaten laden
world <- ne_countries(scale = "medium", returnclass = "sf")

# Selektiere die Spalten 'geometry' und 'name' (Ländername)
world <- world[, c("geometry", "name")]

# Benenne die Spalten um
names(world) <- c("geometry", "Land")

Länder_durchschnitt<- merge(world, new_df, by = "Land", all.x = FALSE)

```


```{r}

# UI Teil für die Shiny-App. Hier wird definiert was man auf der Oberfläche sieht und Auswählen kann
ui <- fluidPage(
  titlePanel(
      h2(paste("Starkniederschläge in Europa"))),
 
  h4(paste("Analyse der Starkniederschläge in Europa in den Jahren 1970-2023")),
  
  tabsetPanel(
    tabPanel("Karte", 
             tags$div(
               style = "border: 4px groove #e0f3f8; padding: 10px;",
               fluidRow(
                 tags$h4("Anzahl Durchschnittliche Regentage in Europa", style = "margin-left: 14px; margin-bottom: 5px; margin-top: 0px; font-size: 16px; "),
                 column(width = 8,
                        leafletOutput("map", width = "100%", height = "600px")
                 ),
                 
                 column(width = 4,
                            radioButtons("Auswahl_Karte", label = ("Kartentyp"),
                                         choices = c("Durchschnitt pro Land","Jeder Datenpunkt einzeln"  ),
                                         selected = "Durchschnitt pro Land",
                                         inline = TRUE)
                          
                        
                 ),
                 column(width = 4,
                   
                     selectInput("intensity", "Niederschlagsintensität:",
                        choices = c( "R99p","R95p", "R75p","20mm", "10mm", "1mm"),
                        selected = "R99p")
      ),
                 column(width = 4,
                        wellPanel(
                          uiOutput("selected_value")
                        )
                 )
               )
             ),
    

             
             tags$div(
               style = "border: 4px groove #e0f3f8; padding: 10px;",
               fluidRow(
                 column(width = 12,
                        sliderInput("year", "Jahr:",
                                    min = min(regendaten$Jahr),
                                    max = max(regendaten$Jahr),
                                    value = min(regendaten$Jahr), 
                                    step = 1,
                                    sep = "",
                                    width = "100%")
                 ),
               
             
             
            
                 
                 
                   
                 column(width = 2,
                          selectInput("month", "Monat:",
                                    choices = c("Jahr", "Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"),
                                    selected = "Jahr")
                        
                 ),
                 column(width = 2,
                        
                        selectInput("country", "Land:",
                                    choices = c("Europa", unique(regendaten$Land)))
                        
                 ),
                 column(width = 2,
                        textOutput("selected_station"))
               )
             ),
             
             tags$div(
               style = "border: 4px groove #e0f3f8; padding: 10px;",
               fluidRow(
                 
                 
                 
                 
                 
                 
                        
                 column(width = 6,
                        plotOutput("plot_Abweichung_vom_Durchschnitt")),
                 column(width = 6,
                        plotOutput("Monate_Vergleich"))
                 
                 
               
                 
                 
                 
                 
                 
                
               )
             )
    ),
    # Zweite Registerkarte für die Anzeige des DataFrames als Tabelle
    tabPanel("Daten",
             navbarPage(
                   title = 'Regendaten',
                   tabPanel('Regendaten von jeder Station',     DT::dataTableOutput('ex1')),
                   tabPanel('Durchschnittswerte pro Land',        DT::dataTableOutput('ex2')))
               )
             
    
    
  )
)     
# Server Teil für die Shiny-App. Hier wird definiert wan welche Daten wo angezeigt werden
server <- function(input, output) {
  
  filtered_data <- reactive({
    data <- regendaten
    if (input$country != "Europa") {
      data <- filter(data, Land %in% input$country)
    }
    if (input$month != "Jahr") {
      month_col <- paste0(input$month, "_Regentage_", input$intensity)
      data <- data %>%
        mutate(Regentage = !!sym(month_col))
    } else {
      intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
      data <- data %>%
        mutate(Regentage = !!sym(intensity_col))
    }
    data <- filter(data, Jahr == input$year)
    
    return(data)
  })
  
 
  
  select_grenzen <- reactive({
   if (input$month == "Jahr") {
    switch(input$intensity,
           "1mm" = c( 0, 1, 41, 81, 121, 161, 201, 241, 281, 321, 361, Inf),
           "10mm" = c( 0, 1, 20, 40, 60, 80, 100, 120, 140, 160,180, Inf),
           "20mm" = c( 0, 1, 14, 27, 40, 53, 66, 79, 92, 105, 120, Inf),
           "R75p" = c( 0, 1, 14, 27, 40, 53, 66, 79, 92, 105, 120, Inf),
           "R95p" = c( 0, 1, 5, 9, 13, 17, 21, 28, 34, 41, 96, Inf),
           "R99p" = c( 0, 1, 3, 5, 7, 9, 11, 14, 17, 21, 96, Inf))
  } else {
    c( 0, 1, 4, 7, 11, 15, 19, 23, 27, 30, 32, Inf)
  }
})

  select_labels <- reactive({
   if (input$month == "Jahr") {
    switch(input$intensity,
           "1mm" = c( "0", "1-40", "41-80", "81-120", "121-160", "161-200", "201-240", "241-280", "281-320", "321-360"),
           "10mm" = c( "0", "1-19", "20-39", "40-59", "60-79", "80-99", "100-119", "120-139", "140-159", "160-179"),
           "20mm" = c( "0", "1-13", "14-26", "27-39", "40-52", "53-65", "66-78", "79-91", "92-104", "105-119"),
           "R75p" = c( "0", "1-13", "14-26", "27-39", "40-52", "53-65", "66-78", "79-91", "92-104", "105-119"),
           "R95p" = c( "0", "1-4", "5-8", "9-12", "13-16", "17-20", "21-27", "28-33", "34-40", "+40"),
           "R99p" = c( "0", "1-2", "3-4", "5-6", "7-8", "9-10", "11-13", "14-16", "17-20", "+20"))
  } else {
    c( "0", "1-3", "4-6", "7-10", "11-14", "15-18", "19-22", "23-26", "27-29", "30-31")
  }
})
  
  select_grenzen_1 <- reactive({
   if (input$month == "Jahr") {
    switch(input$intensity,
           "1mm" = c( 0, 19.8, 39.5, 59.2, 78.9, 98.6, 118.3, 138, 157.7, 177.3, 198, Inf),
           "10mm" = c( 0, 6.7, 13.3, 19.9, 26.5, 33.1, 39.7, 46.3, 52.3, 59.5, 66.1, Inf),
           "20mm" = c( 0, 4.01, 8.01, 12.01, 16.01, 20.01, 24.01, 28.01, 32.01, 36.01,40.01, Inf),
           "R75p" = c( 0, 5.8, 11.5, 17.2, 22.9, 28.6, 34.3, 40, 45.7, 51.4, 57.1, Inf),
           "R95p" = c( 0, 2.2, 4.3, 6.4, 8.5, 10.6, 12.7, 14.8, 16.9, 19, 21.1, Inf),
           "R99p" = c( 0, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3, 5, 5.7, 6.4, 7.1, Inf))
  } else {
      switch(input$intensity,
           "1mm" = c( 0, 3, 5.9, 8.8, 11.7, 14.6, 17.5, 20.4, 23.3, 26.2, 29.1, Inf),
           "10mm" = c( 0, 1.8, 3.5, 5.2, 6.9, 8.6, 10.3, 12, 13.7, 15.4, 17.1, Inf),
           "20mm" = c( 0, 1.3, 2.5, 3.7, 4.9, 6.1, 7.3, 8.5, 9.7, 10.9, 12.1, Inf),
           "R75p" = c( 0, 1.4, 2.7, 4, 5.3, 6.6, 7.9, 9.2, 10.5, 11.8, 13.1, Inf),
           "R95p" = c( 0, 0.8, 1.5, 2.2, 2.9, 3.6, 4.3, 5, 5.7, 6.4, 7.1, Inf),
           "R99p" = c( 0, 0.36, 0.71, 1.06, 1.41, 1.76, 2.11, 2.46, 2.81, 3.16, 3.51, Inf))
  }
})

  select_labels_1 <- reactive({
   if (input$month == "Jahr") {
    switch(input$intensity,
           "1mm" = c("0-19.79", "19.8-39.49", "39.5-59.19", "59.2-78.89", "78.9-98.59", "98.6-118.29", "118.3-137.99", "138-157.69", "157.7-177.29", "177.3-198"),
           "10mm" = c("0-6.69", "6.7-13.29", "13.3-19.89", "19.9-26.49", "26.5-33.09", "33.1-39.69", "39.7-46.29", "46.3-52.29", "52.3-59.49", "59.5-66"),
           "20mm" = c("0-4", "4.01-8", "8.01-12", "12.01-16", "16.01-20", "20.01-24", "24.01-28", "28.01-32", "32.01-36", "36.01-40"),
           "R75p" = c("0-5.79", "5.8-11.49", "11.5-17.19", "17.2-22.89", "22.9-28.59", "28.6-34.29", "34.3-40", "40.01-45.69", "45.7-51.39", "51.4-57"),
           "R95p" = c("0-2.19", "2.2-4.29", "4.3-6.39", "6.4-8.49", "8.5-10.59", "10.6-12.69", "12.7-14.79", "14.8-16.89", "16.9-18.99", "19-21"),
           "R99p" = c("0-0.79", "0.8-1.49", "1.5-2.19", "2.2-2.89", "2.9-3.59", "3.6-4.29", "4.3-4.99", "5-5.69", "5.7-6.39", "6.4-7"))
  } else {
     switch(input$intensity,
           "1mm" = c("0-2.99", "3-5.89", "5.9-8.79", "8.8-11.69", "11.7-14.59", "14.6-17.49", "17.5-20.39", "20.4-23.29", "23.3-26.19", "26.2-29"),
           "10mm" = c("0-1.79", "1.8-3.49", "3.5-5.19", "5.2-6.89", "6.9-8.59", "8.6-10.29", "10.3-11.99", "12-13.69", "13.7-15.39", "15.4-17"),
           "20mm" = c("0-1.29", "1.3-2.49", "2.5-3.69", "3.7-4.89", "4.9-6.09", "6.1-7.29", "7.3-8.49", "8.5-9.69", "9.7-10.89", "10.9-12"),
           "R75p" = c("0-1.39", "1.4-2.69", "2.7-3.99", "4-5.29", "5.3-6.59", "6.6-7.89", "7.9-9.19", "9.2-10.49", "10.5-11.79", "11.8-13"),
           "R95p" = c("0-0.79", "0.8-1.49", "1.5-2.19", "2.2-2.89", "2.9-3.59", "3.6-4.29", "4.3-5", "5.01-5.69", "5.7-6.39", "6.4-7"),
           "R99p" = c("0-0.35", "0.36-0.7", "0.71-1.05", "1.06-1.4", "1.41-1.75", "1.76-2.1", "2.11-2.45", "2.46-2.8", "2.81-3.15", "3.16-3.5"))
  }
})

  
  
  # Definiere die Farben für jede Kategorie der Regentage
  farben <- c("#FFF", "#CFF", "#0FF", "#0CF", "#09F", "#06F", "#03F", 
                "#00F", "#039", "#009")
  
  selected_station_id <- reactiveVal(NULL)
  selected_station_name <- reactiveVal(NULL)
  selected_station_land <- reactiveVal(NULL)
  output$map <- renderLeaflet({
   if (input$Auswahl_Karte == "Jeder Datenpunkt einzeln"){ 
    selected_grenzen <- select_grenzen()
    selected_labels <- select_labels()
    
    default_center <- c(50, 10)  # Standard-Zentrum für den Zoom
    default_zoom <- 4  # Standard-Zoom-Level
    
    
    if (input$country != "Europa") {
      selected_country <- regendaten %>%
        filter(Land == input$country) %>%
        summarise(mean_lat = mean(Breitengrad_d),
              mean_lng = mean(Längengrad_d)) %>%
        as.numeric()
      map_center <- selected_country
      map_zoom <- 6  
    } else {
      map_center <- default_center
      map_zoom <- default_zoom
    }
    
    leaflet() %>%
      setView(lng = map_center[2], lat = map_center[1], zoom = map_zoom) %>%
      addProviderTiles("OpenStreetMap.Mapnik") %>%
      addCircleMarkers(data = filtered_data(),
                       ~Längengrad_d, ~Breitengrad_d, 
                       fill = TRUE,
                       fillOpacity = 1,
                       radius =  4,
                       color = ifelse(is.na(filtered_data()$Regentage), (rgb(0, 0, 255, max = 255, alpha = 0, names = "unsichtbar")), farben[findInterval(filtered_data()$Regentage, selected_grenzen)]),
                       popup = ~paste("Station ID:", Station_ID, "<br>", "Station Name:", Station_Name, "<br>",
                                      "Land:", Land, "<br>", "Jahr:", input$year, "<br>", "Niederschlagsintensität:", input$intensity, "<br>",
                                      "Regentage im ", input$month, ":", Regentage),
                       layerId = ~Station_ID) %>%
      addLegend(position = "bottomright", 
                title = "Regentage", 
                colors = farben, 
                labels = selected_labels, 
                opacity = 1)  
    
      
  }
 else {
  
  
    selected_grenzen_1 <- select_grenzen_1()
    selected_labels_1 <- select_labels_1()
    default_center <- c(50, 10)  
    default_zoom <- 4  
   
    data <- Länder_durchschnitt
    
    if (input$month != "Jahr") {
      month_col <- paste0(input$month, "_Regentage_", input$intensity)
      data <- data %>%
        mutate(Regentage_1 = !!sym(month_col))
    } else {
      intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
      data <- data %>%
        mutate(Regentage_1 = !!sym(intensity_col))
    }
    
    data <- filter(data, Jahr == input$year)
    
    leaflet() %>%
      setView(lng = default_center[2], lat = default_center[1], zoom = default_zoom) %>%
      addProviderTiles("OpenStreetMap.Mapnik") %>%
      addPolygons(data = data,
                  fillColor =  ifelse(is.na(data$Regentage_1), "transparent", 
                                 farben[findInterval(data$Regentage_1, selected_grenzen_1)]),
                  fillOpacity = 0.7,
                  color = "black",
                  weight = 1,
                  popup = ~paste("Land:",Land,"<br>","Durchschnittliche Regentage im ", input$month, ":", data$Regentage_1)) %>%
     
      addLegend(position = "bottomright", 
                title = "Regentage", 
                colors = farben, 
                labels = selected_labels_1, 
                opacity = 1)  
      
  }
})
    
  observeEvent(input$map_marker_click, {
    click_info <- input$map_marker_click
    
    if (!is.null(click_info)) {
      selected_station_id(click_info$id)
      
      clicked_data <- filtered_data()[filtered_data()$Station_ID == click_info$id,]
      if (nrow(clicked_data) > 0) {
        selected_station_name(clicked_data$Station_Name)
        selected_station_land(clicked_data$Land)
      }
    } else {
      selected_station_id(NULL)
      selected_station_name(NULL)
      selected_station_land(NULL)
    }
  })
  
 
  
  
  output$selected_value <- renderUI({
    req(input$country)
    req(input$year)
    req(input$month)
    req(input$intensity)
    intensity_text <- switch(input$intensity,
                             "1mm" = "1 Liter Niederschlag pro Quadratmeter innerhalb von 24 Stunden",
                             "10mm" = "10 Liter Niederschlag pro Quadratmeter innerhalb von 24 Stunden",
                             "20mm" = "20 Liter Niederschlag pro Quadratmeter innerhalb von 24 Stunden",
                             "R75p" = "Anzahl der Tage an welche es mehr geregnet hat als an 75 Prozent der anderen Tage an dieser Messstation, seit Messbeginn",
                             "R95p" = "Anzahl der Tage an welche es mehr geregnet hat als an 95 Prozent der anderen Tage an dieser Messstation, seit Messbeginn",
                             "R99p" = "Anzahl der Tage an welche es mehr geregnet hat als an 99 Prozent der anderen Tage an dieser Messstation, seit Messbeginn")
   
    if (input$country == "Europa"){
      if (input$month != "Jahr") {
        month_col <- paste0(input$month, "_Regentage_", input$intensity)
        value <- new_df %>%
           filter(Jahr == input$year) %>%
           summarise(Durchschnitt_Regentage_aller_Länder1 = mean(!!sym(month_col), na.rm = TRUE))
        value <- value %>%
           summarise(Durchschnitt_Regentage_gesamt1 = mean(Durchschnitt_Regentage_aller_Länder1, na.rm = TRUE)) %>%
           pull() %>%
           round(2)
     }else {
        intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
        value <- new_df %>%
           filter(Jahr == input$year) %>%
           summarise(Durchschnitt_Regentage_aller_Länder1 = mean(!!sym(intensity_col), na.rm = TRUE))
        value <- value %>%
           summarise(Durchschnitt_Regentage_gesamt1 = mean(Durchschnitt_Regentage_aller_Länder1, na.rm = TRUE)) %>%
           pull() %>%
           round(2)
      }
   }else{   
      if (input$month != "Jahr") {
        month_col <- paste0(input$month, "_Regentage_", input$intensity)
        value <- new_df %>%
          filter(Land == input$country, Jahr == input$year) %>%
          select(!!sym(month_col)) %>%
          pull() %>%
          round(2)
     }else {
        intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
        value <- new_df %>%
          filter(Land == input$country, Jahr == input$year) %>%
          select(!!sym(intensity_col)) %>%
          pull() %>%
          round(2)
      }
    }
    wellPanel(
    h4(paste("Info für", input$intensity)),
    p(intensity_text),
    hr(),
    h4(paste("Infos zu Durchschnittswerten in:", input$country )),
    p(paste(value,"Durchschnittliche Regentage im", input$month, input$year, "in", input$country, "bei", input$intensity))
    
  )
  })
  output$Monate_Vergleich <- renderPlot({
   if (is.null(selected_station_id()) | input$Auswahl_Karte == "Durchschnitt pro Land") {
    
     if (input$country != "Europa") {
      data <- new_df


      plot_daten <- data %>% filter(Land == input$country)
      monthly_columns_10mm <- names(plot_daten)[grepl(input$intensity, names(plot_daten)) & !grepl("pro_Jahr", names(plot_daten))]


      switzerland_2020 <- plot_daten %>% filter(Jahr == input$year) %>% select(all_of(monthly_columns_10mm))


      switzerland_avg <- plot_daten %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
      switzerland_avg_70_90 <- plot_daten %>% filter(Jahr >= 1970 & Jahr <= 1996) %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
      switzerland_avg_03_23 <- plot_daten %>% filter(Jahr >= 1997 & Jahr <= 2023) %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
  

      months <- c("Januar","Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")


      data_2020 <- switzerland_2020 %>% gather(key = "Month", value = "Days")
      if (nrow(data_2020) == 0) {
        ggplot() +
          annotate("text", x = 1, y = 1, label = paste("Im Jahr",input$year,"sind zum Land", input$country,"keine Daten verfügbar"), size = 6, color = "red") +
          theme_void()
    } else {
      data_2020$Month <- factor(months, levels = months)
      data_avg <- switzerland_avg %>% gather(key = "Month", value = "Days")
      data_avg$Month <- factor(months, levels = months)
      data_avg_70_90 <- switzerland_avg_70_90 %>% gather(key = "Month", value = "Days")
      data_avg_70_90$Month <- factor(months, levels = months)
    
      data_avg_03_23 <- switzerland_avg_03_23 %>% gather(key = "Month", value = "Days")
      data_avg_03_23$Month <- factor(months, levels = months)
    

      ggplot() +
        geom_line(data = data_2020, aes(x = Month, y = Days, group = 1, color = paste0(input$year)), size = 1) +
        geom_point(data = data_2020, aes(x = Month, y = Days, color = paste0(input$year)), size = 3) +
        geom_line(data = data_avg, aes(x = Month, y = Days, group = 1, color = "Durchschnitt über alle Jahre 1970-2023"), linetype = "dashed", size = 1) +
        geom_point(data = data_avg, aes(x = Month, y = Days, color = "Durchschnitt über alle Jahre 1970-2023"), size = 3) +
        geom_line(data = data_avg_70_90, aes(x = Month, y = Days, group = 1, color = "Durchschnitt 1970-1996"), linetype = "dotted", size = 1, alpha = 0.5) +
        geom_point(data = data_avg_70_90, aes(x = Month, y = Days, color = "Durchschnitt 1970-1996"), size = 2) +
        geom_line(data = data_avg_03_23, aes(x = Month, y = Days, group = 1, color = "Durchschnitt 1997-2023"), linetype = "dotted", size = 1, alpha = 0.5) +
        geom_point(data = data_avg_03_23, aes(x = Month, y = Days, color = "Durchschnitt 1997-2023"), size = 2) +
         labs(x = "Monate", y = "Anzahl Regentage",
          title = paste("Anzahl Regentage über die Monate im Jahr:", input$year,"in", input$country, "bei", input$intensity ),
          color = "Legende") +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 12, face = "bold", angle = 45, hjust = 1),
            axis.text.y = element_text(size = 12, face = "bold"),
            plot.title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 14),  
            axis.title.y = element_text(size = 14),
            legend.title = element_text(size = 14), 
            legend.text = element_text(size = 12),
            legend.position = "bottom")
}
    
  }
      else{
        data <- new_df


    
        monthly_columns_10mm <- names(data)[grepl(input$intensity, names(data)) & !grepl("pro_Jahr", names(data))]


      switzerland_2020 <- data %>% filter(Jahr == input$year) %>% select(all_of(monthly_columns_10mm))
      switzerland_2020 <- switzerland_2020 %>%
        summarise_all(mean,na.rm=TRUE)

      switzerland_avg <- data %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
      switzerland_avg_70_90 <- data %>% filter(Jahr >= 1970 & Jahr <= 1996) %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
      switzerland_avg_03_23 <- data %>% filter(Jahr >= 1997 & Jahr <= 2023) %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))


      months <- c("Januar","Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")


      data_2020 <- switzerland_2020 %>% gather(key = "Month", value = "Days")
    
    
      data_2020$Month <- factor(months, levels = months)
      data_avg <- switzerland_avg %>% gather(key = "Month", value = "Days")
      data_avg$Month <- factor(months, levels = months)
      data_avg_70_90 <- switzerland_avg_70_90 %>% gather(key = "Month", value = "Days")
      data_avg_70_90$Month <- factor(months, levels = months)
  
      data_avg_03_23 <- switzerland_avg_03_23 %>% gather(key = "Month", value = "Days")
      data_avg_03_23$Month <- factor(months, levels = months)
    
    


      ggplot() +
        geom_line(data = data_2020, aes(x = Month, y = Days, group = 1, color = paste0(input$year)), size = 1) +
        geom_point(data = data_2020, aes(x = Month, y = Days, color = paste0(input$year)), size = 3) +
        geom_line(data = data_avg, aes(x = Month, y = Days, group = 1, color = "Durchschnitt über alle Jahre 1970-2023"), linetype = "dashed", size = 1) +
        geom_point(data = data_avg, aes(x = Month, y = Days, color = "Durchschnitt über alle Jahre 1970-2023"), size = 3) +
        geom_line(data = data_avg_70_90, aes(x = Month, y = Days, group = 1, color = "Durchschnitt 1970-1996"), linetype = "dotted", size = 1, alpha = 0.5) +
        geom_point(data = data_avg_70_90, aes(x = Month, y = Days, color = "Durchschnitt 1970-1996"), size = 2) +
        geom_line(data = data_avg_03_23, aes(x = Month, y = Days, group = 1, color = "Durchschnitt 1997-2023"), linetype = "dotted", size = 1, alpha = 0.5) +
        geom_point(data = data_avg_03_23, aes(x = Month, y = Days, color = "Durchschnitt 1997-2023"), size = 2) +
        labs(x = "Monate", y = "Anzahl Regentage",
           title = paste("Anzahl Regentage über die Monate im Jahr", input$year,"in", input$country, "bei", input$intensity ),
           color = "Legende") +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 12, face = "bold", angle = 45, hjust = 1),
            axis.text.y = element_text(size = 12, face = "bold"),
            plot.title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 14),  
            axis.title.y = element_text(size = 14),
            legend.title = element_text(size = 14),  
            legend.text = element_text(size = 12),
            legend.position = "bottom")
      }
   }else{
     data <- regendaten[regendaten$Station_ID == selected_station_id(), ]


    
      monthly_columns_10mm <- names(data)[grepl(input$intensity, names(data)) & !grepl("pro_Jahr", names(data))]


      switzerland_2020 <- data %>% filter(Jahr == input$year) %>% select(all_of(monthly_columns_10mm))
      switzerland_2020 <- switzerland_2020 %>%
        summarise_all(mean,na.rm=TRUE)

      switzerland_avg <- data %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
      switzerland_avg_70_90 <- data %>% filter(Jahr >= 1970 & Jahr <= 1996) %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))
      switzerland_avg_03_23 <- data %>% filter(Jahr >= 1997 & Jahr <= 2023) %>% select(all_of(monthly_columns_10mm)) %>% summarise(across(everything(), mean, na.rm = TRUE))


      months <- c("Januar","Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember")


      data_2020 <- switzerland_2020 %>% gather(key = "Month", value = "Days")
      
     
      data_2020$Month <- factor(months, levels = months)
      data_avg <- switzerland_avg %>% gather(key = "Month", value = "Days")
      data_avg$Month <- factor(months, levels = months)
      data_avg_70_90 <- switzerland_avg_70_90 %>% gather(key = "Month", value = "Days")
      data_avg_70_90$Month <- factor(months, levels = months)
  
      data_avg_03_23 <- switzerland_avg_03_23 %>% gather(key = "Month", value = "Days")
      data_avg_03_23$Month <- factor(months, levels = months)
    
    
      ggplot() +
        geom_line(data = data_2020, aes(x = Month, y = Days, group = 1, color = paste0(input$year)), size = 1) +
        geom_point(data = data_2020, aes(x = Month, y = Days, color = paste0(input$year)), size = 3) +
        geom_line(data = data_avg, aes(x = Month, y = Days, group = 1, color = "Durchschnitt über alle Jahre 1970-2023"), linetype = "dashed", size = 1) +
        geom_point(data = data_avg, aes(x = Month, y = Days, color = "Durchschnitt über alle Jahre 1970-2023"), size = 3) +
        geom_line(data = data_avg_70_90, aes(x = Month, y = Days, group = 1, color = "Durchschnitt 1970-1996"), linetype = "dotted", size = 1, alpha = 0.5) +
        geom_point(data = data_avg_70_90, aes(x = Month, y = Days, color = "Durchschnitt 1970-1996"), size = 2) +
        geom_line(data = data_avg_03_23, aes(x = Month, y = Days, group = 1, color = "Durchschnitt 1997-2023"), linetype = "dotted", size = 1, alpha = 0.5) +
        geom_point(data = data_avg_03_23, aes(x = Month, y = Days, color = "Durchschnitt 1997-2023"), size = 2) +
        labs(x = "Monate", y = "Anzahl Regentage",
           title = paste("Anzahl Regentage über die Monate im Jahr", input$year,"bei der Messstation",selected_station_name(),"(Id:",selected_station_id(), ")", "in", selected_station_land(),  "bei", input$intensity ),
           color = "Legende") +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 12, face = "bold", angle = 45, hjust = 1),
            axis.text.y = element_text(size = 12, face = "bold"),
            plot.title = element_text(size = 10, face = "bold"),
            axis.title.x = element_text(size = 14),  
            axis.title.y = element_text(size = 14),
            legend.title = element_text(size = 14),  
            legend.text = element_text(size = 12),
            legend.position = "bottom")
     
   }
})


  output$plot_Abweichung_vom_Durchschnitt <- renderPlot({
   if (is.null(selected_station_id()) | input$Auswahl_Karte == "Durchschnitt pro Land") {
    if (input$country != "Europa" ) {
      land_df <- subset(new_df, Land == input$country)
    
      if (input$month != "Jahr") {
      intensity_col <- paste0(input$month,"_Regentage_", input$intensity)
      title <- paste("Abweichung der Regentage im", input$month,"in", input$country, "bei", input$intensity, "vom Gesamtdurchschnitt")
    }  else {
       intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
       title <- paste("Abweichung der Regentage pro Jahr in", input$country, "bei", input$intensity, "vom Gesamtdurchschnitt")
    }

       
    land_durchschnitt <- land_df %>%
      summarise(Durchschnitt_Regentage = mean(!!sym(intensity_col), na.rm = TRUE)) %>%
      pull(Durchschnitt_Regentage)
    

      
    land_df$Abweichung_vom_schnitt <- land_df[[intensity_col]] - land_durchschnitt

      
    ggplot(land_df, aes(x = Jahr, y = Abweichung_vom_schnitt)) +
     geom_bar(stat = "identity", aes(fill = Abweichung_vom_schnitt > 0), width = 0.7) +
     geom_hline(aes(yintercept = 0, color = "Schnitt"), linetype = "solid") +
     geom_smooth(method = "lm", se = FALSE, linetype = "dashed", size = 1, aes(color = "Trendlinie")) +
     labs(title = title, x = "Jahr", y = "Abweichung vom Durchschnitt über alle Jahre")+
     scale_fill_manual(values = c("#FB9A99","#A6CEE3"),
                    name = "",
                    labels = c( "Unter dem Schnitt","Über dem Schnitt")) +
     scale_color_manual(values = c( "black","purple"),
                     name = "",
                     labels = c(paste("Gesamtdurchschnitt von 1970-2023:", round(land_durchschnitt,2), "Regentage"),"Trendlinie"))+
     theme(axis.text.x = element_text(size = 12, face = "bold"),
            axis.text.y = element_text(size = 12, face = "bold"),
            plot.title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 14),  
            axis.title.y = element_text(size = 14),
            legend.title = element_text(size = 14),  #
            legend.text = element_text(size = 12),
            legend.position = "bottom")
     
  }  else {
       if (input$month != "Jahr") {
        intensity_col <- paste0(input$month,"_Regentage_", input$intensity)
       title <- paste("Abweichung der Regentage im", input$month,"in", input$country, "bei", input$intensity, "vom Gesamtdurchschnitt")
    }   else {
         intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
         title <- paste("Abweichung der Regentage pro Jahr in", input$country, "bei", input$intensity, "vom Gesamtdurchschnitt")
    }
    
      average_regentage_aller_Länder3 <- new_df %>%
        group_by(Jahr) %>%
        summarise(Durchschnitt_Regentage_aller_Länder3 = mean(!!sym(intensity_col), na.rm = TRUE))





     land_durchschnitt3 <- mean(average_regentage_aller_Länder3$Durchschnitt_Regentage_aller_Länder3, na.rm = TRUE)


     average_regentage_aller_Länder3$Abweichung_vom_schnitt3 <- average_regentage_aller_Länder3$Durchschnitt_Regentage_aller_Länder3 - land_durchschnitt3


     ggplot(average_regentage_aller_Länder3, aes(x = Jahr, y = Abweichung_vom_schnitt3)) +
       geom_bar(stat = "identity", aes(fill = Abweichung_vom_schnitt3 > 0), width = 0.7) +
       geom_hline(aes(yintercept = 0, color = "Schnitt"), linetype = "solid") +
       geom_smooth(method = "lm", se = FALSE, linetype = "dashed", size = 1, aes(color = "Trendlinie")) +
       labs(title = title, x = "Jahr", y = "Abweichung vom Durchschnitt über alle Jahre") +
       scale_fill_manual(values = c( "#FB9A99","#A6CEE3"),
                    name = "",
                    labels = c( "Unter dem Schnitt","Über dem Schnitt")) +
       scale_color_manual(values = c( "black","purple"),
                     name = "",
                     labels = c(paste("Gesamtdurchschnitt von 1970-2023:", round(land_durchschnitt3,2), "Regentage"),"Trendlinie"))+
       theme(axis.text.x = element_text(size = 12, face = "bold"),
            axis.text.y = element_text(size = 12, face = "bold"),
            plot.title = element_text(size = 14, face = "bold"),
            axis.title.x = element_text(size = 14),  
            axis.title.y = element_text(size = 14),
            legend.title = element_text(size = 14),  
            legend.text = element_text(size = 12),
            legend.position = "bottom")
  }}
   else {
     if (input$month != "Jahr") {
        intensity_col <- paste0(input$month,"_Regentage_", input$intensity)
       title <- paste("Abweichung der Regentage im", input$month,"bei der Messstation",selected_station_name(),"(Id:",selected_station_id(), ")", "in", selected_station_land(),  "bei", input$intensity,"vom Gesamtdurchschnitt," )
    }   else {
         intensity_col <- paste0("Regentage_pro_Jahr_", input$intensity)
         title <- paste("Abweichung der Regentage pro Jahr bei der Messstation",selected_station_name(),"(Id:",selected_station_id(), ")", "in", selected_station_land(),  "bei", input$intensity, "vom Gesamtdurchschnitt" )
    }
     new_df1 <- regendaten[regendaten$Station_ID == selected_station_id(), ]
     average_regentage_aller_Länder3 <- new_df1 %>%
        group_by(Jahr) %>%
        summarise(Durchschnitt_Regentage_aller_Länder3 = mean(!!sym(intensity_col), na.rm = TRUE))





     land_durchschnitt3 <- mean(average_regentage_aller_Länder3$Durchschnitt_Regentage_aller_Länder3, na.rm = TRUE)


     average_regentage_aller_Länder3$Abweichung_vom_schnitt3 <- average_regentage_aller_Länder3$Durchschnitt_Regentage_aller_Länder3 - land_durchschnitt3


     ggplot(average_regentage_aller_Länder3, aes(x = Jahr, y = Abweichung_vom_schnitt3)) +
       geom_bar(stat = "identity", aes(fill = Abweichung_vom_schnitt3 > 0), width = 0.7) +
       geom_hline(aes(yintercept = 0, color = "Schnitt"), linetype = "solid") +
       geom_smooth(method = "lm", se = FALSE, linetype = "dashed", size = 1, aes(color = "Trendlinie")) +
       labs(title = title, x = "Jahr", y = "Abweichung vom Durchschnitt über alle Jahre") +
       scale_fill_manual(values = c( "#FB9A99","#A6CEE3"),
                    name = "",
                    labels = c( "Unter dem Schnitt","Über dem Schnitt")) +
       scale_color_manual(values = c( "black","purple"),
                     name = "",
                     labels = c(paste("Gesamtdurchschnitt von 1970-2023:", round(land_durchschnitt3,2), "Regentage"),"Trendlinie"))+
       theme(axis.text.x = element_text(size = 12, face = "bold"),
            axis.text.y = element_text(size = 12, face = "bold"),
            plot.title = element_text(size = 10, face = "bold"),
            axis.title.x = element_text(size = 14),  
            axis.title.y = element_text(size = 14),
            legend.title = element_text(size = 14),  
            legend.text = element_text(size = 12),
            legend.position = "bottom")
    }


})
  
  
  output$ex1 <- DT::renderDataTable(
    DT::datatable(regendaten, options = list(searching = FALSE))
  )
  output$ex2 <- DT::renderDataTable(
    DT::datatable(new_df)
  )



}
  
shinyApp(ui = ui, server = server)

```
